# Generated by Django 4.2.28 on 2026-03-04 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogo", "0002_imagenproducto"),
    ]

    operations = [
        migrations.AlterField(
            model_name="imagenproducto",
            name="imagen",
            field=models.ImageField(upload_to="productos/"),
        ),
    ]
