# Generated by Django 4.2.28 on 2026-03-17 20:51

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("catalogo", "0004_pedido_detallepedido"),
    ]

    operations = [
        migrations.CreateModel(
            name="Cupon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("codigo", models.CharField(max_length=20, unique=True)),
                (
                    "descuento_porcentaje",
                    models.IntegerField(
                        help_text="Porcentaje de descuento (1 a 100)",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                ("valido_desde", models.DateTimeField()),
                ("valido_hasta", models.DateTimeField()),
                ("limite_usos", models.PositiveBigIntegerField(default=100)),
                ("usos_actuales", models.PositiveBigIntegerField(default=0)),
                ("activo", models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name="pedido",
            name="descuento_aplicado",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name="pedido",
            name="total",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="pedido",
            name="cupon",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="catalogo.cupon",
            ),
        ),
    ]
