# Generated by Django 4.2.28 on 2026-03-22 23:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        (
            "catalogo",
            "0005_cupon_pedido_descuento_aplicado_alter_pedido_total_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="pedido",
            name="usuario",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pedidos",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
