# Generated by Django 4.2.28 on 2026-03-23 00:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("catalogo", "0006_pedido_usuario"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pedido",
            name="usuario",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="pedidos",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
