# Generated by Django 4.2.28 on 2026-03-24 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogo", "0008_comentario"),
    ]

    operations = [
        migrations.AddField(
            model_name="pedido",
            name="tracking_id",
            field=models.CharField(
                blank=True,
                max_length=100,
                null=True,
                verbose_name="Número de Seguimiento",
            ),
        ),
        migrations.AlterField(
            model_name="pedido",
            name="estado",
            field=models.CharField(
                choices=[
                    ("pendiente", "⏳ Pendiente"),
                    ("pagado", "✅ Pagado"),
                    ("preparacion", "📦 En Preparación"),
                    ("enviado", "🚚 Enviado"),
                    ("entregado", "🏠 Entregado"),
                    ("cancelado", "❌ Cancelado"),
                ],
                default="pendiente",
                max_length=20,
            ),
        ),
    ]
