# Generated by Django 4.2.28 on 2026-03-25 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogo", "0010_alter_pedido_estado"),
    ]

    operations = [
        migrations.AddField(
            model_name="pedido",
            name="email",
            field=models.EmailField(
                default=True, max_length=254, verbose_name="Correo electrónico"
            ),
            preserve_default=False,
        ),
    ]
