# Generated by Django 4.2.28 on 2026-03-25 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogo", "0012_alter_pedido_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pedido",
            name="email",
            field=models.EmailField(max_length=254, verbose_name="Correo electrónico"),
        ),
    ]
