# Generated by Django 4.2.28 on 2026-03-25 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogo", "0013_alter_pedido_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pedido",
            name="email",
            field=models.EmailField(
                blank=True, max_length=254, null=True, verbose_name="Correo electrónico"
            ),
        ),
    ]
